export const TYPES = {
	_app: Symbol.for('app'),
	_apiPack:  Symbol.for('_apiPack'),
	_productsApi:  Symbol.for('_productsApi'),
	_categoriesApi:  Symbol.for('_categoriesApi'),
	_usersApi:  Symbol.for('_usersApi'),
	_cartApi:  Symbol.for('_cartApi'),
	_chatsApi: Symbol.for('_chatsApi'),
	_socketApi: Symbol.for('_socketApi'),
	_restAdapter: Symbol.for('_restAdapter'),
	_socketIOAdapter: Symbol.for('_socketIOAdapter'),
  _websocketAdapter: Symbol.for('_websocketAdapter'),
	_api: Symbol.for('_api'),
	_authApi: Symbol.for('_authApi'),
	_ordersApi:  Symbol.for('_ordersApi'),
}